### ISSUE TITLE
Ошибка компиляции: "fatal error: pins_arduino.h: No such file or directory"

### ISSUE THREAD

**Issue by RayzFoxx** [AlexGyver/GyverCore#1]
При попытке компиляции кода для работы с MPU6050 (Использовал пример из библиотеки MPU6050_DMP_6) возникает следующая ошибка:

` C:\Users\RayzFoxx\AppData\Local\Arduino15\packages\GyverCore\hardware\avr\1.1.0\libraries\Wire\src\utility\twi.c:38:26: fatal error: pins_arduino.h: No such file or directory

 #include "pins_arduino.h"

                          ^

compilation terminated.

exit status 1
Ошибка компиляции для платы ATmega328/168 based.
`

Версия IDE: 1.8.5
Версия ядра: 1.1.0

**Comment by AlexGyver** [comment]
Не думал, что сторонние библиотеки будут трогать костыли из pins_arduino. Придется его вернуть, спасибо

**Comment by AlexGyver** [comment]
Обнови ядро через менеджер, должно работать. Попробовал несколько библиотек, всё ок

**Comment by RayzFoxx** [comment]
Обновил, код скомпилировался и теперь работает. Спасибо)
