### ISSUE TITLE
Use with PlatformIO and VS Code

### ISSUE THREAD

**Issue by Slenkis** [AlexGyver/GyverCore#10]
Есть ли гайд как установить ядро в платформио под линухом?

**Comment by AlexGyver** [comment]
Уууу ууууу уууу
Нет

**Comment by Slenkis** [comment]
Но я все равно ядро поставил. Было просто.

**Comment by AlexGyver** [comment]
Если накидаешь инструкцию - добавим в основной гайд, я с линуксом вообще не знаком

**Comment by Slenkis** [comment]
Если не секрет, то в какой IDE пишешь код ядра?

**Comment by AlexGyver** [comment]
Зачем IDE?) Блокнот++, большего не надо

**Comment by Slenkis** [comment]
Если ты не шутишь, то держи ошибки в GyverUART
![err1](https://user-images.githubusercontent.com/30866426/71581118-dfa9aa00-2b14-11ea-8544-8fec02464b99.png)
![err2](https://user-images.githubusercontent.com/30866426/71581119-dfa9aa00-2b14-11ea-8600-633cffe3b4ca.png)

**Comment by AlexGyver** [comment]
Хм, не знаю что ему не нравится

**Comment by turbosnail** [comment]
Если я правильно понимаю, описывается метод, у которого в параметрах int8_t, int16_t, int32_t, но внутри метода вызывается printHelper, в котором идет явное преобразование в long.  
Видимо надо учитывать размер переменной, возможно int16_t = 16 bits, а long = 32 bits

**Comment by AlexGyver** [comment]
Да, ничего не мешает 8 битному целому преобразоваться в 32 битное

**Comment by willtek85** [comment]
> Но я все равно ядро поставил. Было просто.

Поделись, пожалуйста, как ты это сделал.
Спасибо.

**Comment by Slenkis** [comment]
> > Я все равно ядро ​​поставил. Было просто.
> 
> Сленкис, поделись, пожалуйста.
> Спасибо.

Я его поставил, но работать оно отказывается. Да и делал я все в CLion. Но могу тебя в CLion создавать проект Platformio, который на стоковом ядре, но полностью работает.

**Comment by AlexGyver** [comment]
Надо читать, какие требования к репозиториям для платформио, я с ним вообще не работал
