### ISSUE TITLE
Strange word usage

### ISSUE THREAD

**Issue by donRumata03** [AlexGyver/GyverCore#14]
В файле README_eng.md
"""
a bunch of interesting staff is added
"""
Может быть, всё-таки, stuff?..

**Comment by AlexGyver** [comment]
Может быть)))))))))))

**Comment by donRumata03** [comment]
А то получается, что добавлен персонал...

**Comment by RayzFoxx** [comment]
В таком случае это уже Фиксики)

**Comment by AlexGyver** [comment]
> В таком случае это уже Фиксики)

Ахахахахахахахахахаха они кстати и правда есть там
