### ISSUE TITLE
При использовании Clock: Internal 8MHz все замедляется в два раза

### ISSUE THREAD

**Issue by vitaliy172** [AlexGyver/GyverCore#22]
Наверное, код для 8МГц и для 16МГц одинаковый

**Comment by AlexGyver** [comment]
Что именно замедляется? Фьюзы перепрошиты на 8 МГц?

**Comment by vitaliy172** [comment]
delay замедляется ровно в 2 раза

**Comment by AlexGyver** [comment]
Фьюзы перепрошиты на 8 МГц?
