### ISSUE TITLE
Ошибка при загрузке скетча с GYVERCORE

### ISSUE THREAD

**Issue by MisterMaxVel** [AlexGyver/GyverCore#23]
Установил GYVERCORE по инструкции, в менеджере плат все установилось, но при попытке прошить любой скетч, к примеру Blink выдает ошибку "**avrdude: stk500_recv(): programmer is not responding**" - это часть ошибки. Видно что скетч компилируется, после пытается загрузится на плату Arduino UNO несколько раз вспыхивает светодиод TX и уходит в ошибку. Пробовал кучу вариантов, все переставлял по 10 раз, но ничего не получилось. Не пойму куда копать. Внизу файл с полным описанием ошибки
[Новый текстовый документ (2).txt](https://github.com/AlexGyver/GyverCore/files/5738412/2.txt)

**Comment by AlexGyver** [comment]
Значит выбрана несоответствующая версия загрузчика, а на уно может быть неизвестно какой и не факт что в гуверкоре есть такой. Лучше прошить optiboot из списка доступных

**Comment by MisterMaxVel** [comment]
Разобрался, большое спасибо!
