### ISSUE TITLE
New core update

### ISSUE THREAD

**Issue by demosspro** [AlexGyver/GyverCore#25]
Приветствую, будут ли новые апдейты ядра?
С платами на 168 будет совместимость?

**Comment by GyverLibs** [comment]
Привет, обновлять к счастью нечего. От поддержки 168 отказались почти в самом начале, при желании можно использовать ядро miniCore, оно не сильно тяжелее

**Comment by demosspro** [comment]
Спасибо за ответ! У меня просто пачка 168 осталась с былых времён. :) 
Удачи в разработках и не только!

**Comment by GyverLibs** [comment]
Спасибо) используй minicore, там есть все настройки камня в меню
