### ISSUE TITLE
Добавление LGT8F328p

### ISSUE THREAD

**Issue by pust0ta** [AlexGyver/GyverCore#30]
Реально ли добавить возможность работы с LGT8F328p в GyverCore?
На мой дилетантский взгляд, по-минимуму нужно добавить частоту 32МГц, а в идеале "подружить" GyverCore c расширенным функционалом чипа.

**Comment by GyverLibs** [comment]
Зачем? У lgt8 своё ядро хорошее, с учётом всех возможностей чипа

**Comment by pust0ta** [comment]
Если их ядро схоже по оптимизации с GyverCore, то и не зачем.
