### ISSUE TITLE
Пины A6 и A7 работают некорректно

### ISSUE THREAD

**Issue by ArtyuhovVadim** [AlexGyver/GyverCore#32]
```cpp 
void setup()
{
  Serial.begin(9600);
}

void loop()
{
  auto a6 = analogRead(A6);
  auto a7 = analogRead(A7);

  Serial.print(a6);
  Serial.print("   ");
  Serial.println(a7);
}
```

По схеме к пинам A6 и A7 подключены кнопки с подтягивающим резистором к +5 В, то есть при нажатии на кнопку analogRead должен выдавать 0, при отпускании 1023. Оно так и работает, но только если использовать analogRead либо на А6, либо на А7, не вместе, как в коде выше. Сейчас эта работает так: при нажатии на кнопку, подключенную к А6, значение из функции ~400, на другой кнопке ~600, с кнопкой подключенной к А7 аналогичная ситуация, только цифры меняются местами. Также, если нажать одновременно на обе кнопки, то на обоих пинах будет 0. При выборе стандартного ядра код выше начинает работать правильно, естественно без изменений в нем, то есть A6 и A7 перестают быть связаны черной магией. Все расширенные настройки ядра стоят по дефолту, версия ядра 2.0.4

**Comment by GyverLibs** [comment]
По умолчанию АЦП разогнан, добавь хотя бы дилеи между чтениями. Или верни настройки как в ардуино analogPrescaler(128)

**Comment by ArtyuhovVadim** [comment]
Дилеи не помогли, а вот analogPrescaler(128) работает отлично, спасибо!
