### ISSUE TITLE
Update problem  v-1.10.2

### ISSUE THREAD

**Issue by dekorator226** [AlexGyver/GyverCore#7]
> <a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2019/11/21/97bceb96ac0ea15242042923acbeb295-full.jpg" border="0"/></a>
v-1.10.2
arduino ide - 1.8.10

**Comment by AlexGyver** [comment]
Удали установленное все, перезапусти ide

**Comment by dekorator226** [comment]
Спасибо помогло. 
Переход между предыдущими версиями, таких ошибок не выдавал.

**Comment by AlexGyver** [comment]
Да IDE бывает выкидывает всякие приколы, пока не перезапустишь
