### ISSUE TITLE
Перенос body функций внутрь объявления класса.

### ISSUE THREAD

**Issue by Den-W** [AlexGyver/GyverCore#9]
Добрый день,

Пожалуйста перенесите реализацию функций внутрь объявлений класса если класс реализован только в .h и не использует .cpp файла.

Например в GyverPID.h, GyverBME280.h итд.

В текущем виде если проект состоит из нескольких ino\cpp файлов нельзя включить Gyver*.h заголовки в один файл main.h (к примеру) чтобы потом main.h включить во все файлы проекта.

**Comment by AlexGyver** [comment]
Привет, так не включай main во все файлы, зачем и кто так делает?)
